"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import {
  Sparkles,
  Wand2,
  ArrowRight,
  PencilLine,
  CheckCircle2,
  Archive,
  SlidersHorizontal,
  Download,
  CheckSquare,
  Square,
  X,
} from "lucide-react";
import { PageHeader } from "@/components/ui/PageHeader";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { EmptyState } from "@/components/ui/EmptyState";
import { Tabs } from "@/components/ui/Tabs";
import { useAppState } from "@/lib/store";
import { useClientQuery } from "@/lib/clients/use-client-query";

type ApiScript = {
  id: string;
  platform: string;
  format: string;
  title: string | null;
  hook: string | null;
  status: "draft" | "approved" | "used" | "archived";
  created_at: string;
  approved_at: string | null;
  linked_sequence_id: string | null;
};

type StatusFilter = "draft" | "approved" | "used" | "all";

const FORMAT_LABELS: Record<string, string> = {
  reel: "Reel",
  longform: "Long-form",
  vsl: "VSL",
  story_sequence: "Story sequence",
  email: "Email",
};

const STATUS_LABELS: Record<ApiScript["status"], string> = {
  draft: "Draft",
  approved: "Approved",
  used: "Used",
  archived: "Archived",
};

const STATUS_TONE: Record<
  ApiScript["status"],
  "neutral" | "accent" | "green"
> = {
  draft: "neutral",
  approved: "accent",
  used: "green",
  archived: "neutral",
};

export default function ScriptsPage() {
  const router = useRouter();
  const { profile, showToast } = useAppState();
  const clientQ = useClientQuery();
  const [scripts, setScripts] = useState<ApiScript[] | null>(null);
  const [tab, setTab] = useState<StatusFilter>("draft");
  const [generating, setGenerating] = useState(false);
  const [selectMode, setSelectMode] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  const load = useCallback(async () => {
    try {
      const res = await fetch(`/api/scripts${clientQ.q}`, { credentials: "include" });
      if (!res.ok) {
        setScripts([]);
        return;
      }
      const json = (await res.json()) as { scripts: ApiScript[] };
      setScripts(json.scripts);
    } catch {
      setScripts([]);
    }
  }, [clientQ.q]);

  useEffect(() => {
    /* eslint-disable-next-line react-hooks/set-state-in-effect --- one-shot bootstrap */
    void load();
  }, [load]);

  const filtered = useMemo(() => {
    if (!scripts) return null;
    if (tab === "all") return scripts.filter((s) => s.status !== "archived");
    return scripts.filter((s) => s.status === tab);
  }, [scripts, tab]);

  const counts = useMemo(() => {
    const c = { draft: 0, approved: 0, used: 0, archived: 0, all: 0 };
    if (!scripts) return c;
    for (const s of scripts) {
      c[s.status]++;
      if (s.status !== "archived") c.all++;
    }
    return c;
  }, [scripts]);

  /* Default Generate uses the user's script_preferences (Reel + Instagram if
     unset). The /scripts/new page (future) overrides per-generation. */
  async function generateOne() {
    if (generating) return;
    setGenerating(true);
    try {
      const res = await fetch(`/api/scripts/generate${clientQ.q}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({
          platform: profile?.platforms?.[0] ?? "instagram",
          format: "reel",
        }),
      });
      if (!res.ok) {
        const err = (await res.json().catch(() => ({}))) as { error?: string };
        showToast(`Couldn't generate: ${err.error ?? res.status}`);
        setGenerating(false);
        return;
      }
      const json = (await res.json()) as { script: ApiScript };
      router.push(`/scripts/${json.script.id}`);
    } catch {
      showToast("Network error. Try again.");
      setGenerating(false);
    }
  }

  function toggleSelected(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function exitSelectMode() {
    setSelectMode(false);
    setSelected(new Set());
  }

  function exportSelected() {
    if (selected.size === 0) return;
    const ids = Array.from(selected).join(",");
    /* `?ids=...` is the first param; clientQ.amp prepends `&` when needed. */
    window.open(
      `/api/scripts/export-batch?ids=${encodeURIComponent(ids)}${clientQ.amp}`,
      "_blank",
    );
  }

  return (
    <>
      <PageHeader
        title="Scripts"
        description="Generated by AI from your offer, niche, and top-performing transcripts. Review, approve, ship."
        actions={
          <div className="flex items-center gap-1.5">
            {selectMode ? (
              <Button variant="ghost" size="sm" onClick={exitSelectMode}>
                <X className="w-3.5 h-3.5" /> Cancel
              </Button>
            ) : (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setSelectMode(true)}
                disabled={!scripts || scripts.length === 0}
              >
                <CheckSquare className="w-3.5 h-3.5" /> Select
              </Button>
            )}
            <Button
              variant="outline"
              size="sm"
              onClick={() => router.push("/scripts/new")}
            >
              <SlidersHorizontal className="w-3.5 h-3.5" /> Customize
            </Button>
            <Button onClick={generateOne} disabled={generating}>
              <Sparkles className="w-3.5 h-3.5" />
              {generating ? "Generating…" : "Quick generate"}
            </Button>
          </div>
        }
      />

      <div className="mb-4 flex items-center justify-between gap-3">
        <Tabs<StatusFilter>
          value={tab}
          onChange={setTab}
          options={[
            { value: "draft", label: `Drafts${counts.draft > 0 ? ` · ${counts.draft}` : ""}` },
            { value: "approved", label: `Approved${counts.approved > 0 ? ` · ${counts.approved}` : ""}` },
            { value: "used", label: `Used${counts.used > 0 ? ` · ${counts.used}` : ""}` },
            { value: "all", label: `All${counts.all > 0 ? ` · ${counts.all}` : ""}` },
          ]}
        />
        <div className="text-[12px] text-muted hidden sm:block">
          Defaults set in{" "}
          <button
            onClick={() => router.push("/settings")}
            className="text-accent hover:text-accent-2 cursor-pointer font-medium"
          >
            Settings
          </button>
        </div>
      </div>

      {scripts === null ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <div
              key={i}
              className="h-[148px] rounded-[14px] bg-surface-2 border border-border animate-pulse"
            />
          ))}
        </div>
      ) : scripts.length === 0 ? (
        <EmptyState
          icon={<Wand2 className="w-6 h-6" />}
          title="No scripts yet."
          description="Generate your first script — it pulls context from your onboarding profile and any transcripts in /content-dna."
          showSampleDataCta={false}
          primaryAction={{
            label: "Generate script",
            onClick: generateOne,
          }}
        />
      ) : filtered && filtered.length === 0 ? (
        <Card>
          <div className="text-center py-8">
            <div className="text-[13.5px] text-text font-medium">
              No {STATUS_LABELS[tab as ApiScript["status"]]?.toLowerCase() ?? "scripts"} here.
            </div>
            <div className="text-[12px] text-muted mt-1 max-w-[420px] mx-auto">
              {tab === "approved" || tab === "used"
                ? "Approve a draft to move it here. Approved scripts also show up on your Calendar tagged 'Script Ready'."
                : "Switch tabs to find scripts in other states."}
            </div>
          </div>
        </Card>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {filtered!.map((s) => (
            <ScriptTile
              key={s.id}
              script={s}
              selectMode={selectMode}
              isSelected={selected.has(s.id)}
              onClick={() => {
                if (selectMode) toggleSelected(s.id);
                else router.push(`/scripts/${s.id}`);
              }}
            />
          ))}
        </div>
      )}

      {selectMode && selected.size > 0 && (
        <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-40 bg-text text-white shadow-[0_12px_32px_rgba(11,31,58,0.30)] rounded-[14px] px-4 py-2.5 flex items-center gap-3">
          <span className="text-[13px] font-medium tabular-nums">
            {selected.size} selected
          </span>
          <span className="w-px h-4 bg-white/20" />
          <Button size="sm" onClick={exportSelected}>
            <Download className="w-3.5 h-3.5" /> Export PDF
          </Button>
          <button
            onClick={exitSelectMode}
            className="text-white/70 hover:text-white p-1 cursor-pointer"
            aria-label="Cancel"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      )}
    </>
  );
}

function ScriptTile({
  script,
  selectMode,
  isSelected,
  onClick,
}: {
  script: ApiScript;
  selectMode: boolean;
  isSelected: boolean;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className={
        "lift block w-full text-left rounded-[14px] border bg-surface card-base p-4 cursor-pointer relative " +
        (selectMode && isSelected
          ? "border-accent/60 ring-2 ring-accent/20"
          : "border-border")
      }
    >
      {selectMode && (
        <span className="absolute top-3 right-3 w-5 h-5 rounded-md grid place-items-center bg-surface-2 border border-border text-muted">
          {isSelected ? (
            <CheckSquare className="w-4 h-4 text-accent" />
          ) : (
            <Square className="w-4 h-4" />
          )}
        </span>
      )}
      <div className="flex items-center gap-1.5 mb-2.5">
        <Badge tone={STATUS_TONE[script.status]}>
          {STATUS_LABELS[script.status]}
        </Badge>
        <Badge tone="neutral">{FORMAT_LABELS[script.format] ?? script.format}</Badge>
        <Badge tone="neutral">{script.platform}</Badge>
      </div>
      <div className="text-[14px] font-semibold tracking-[-0.005em] text-text leading-tight line-clamp-2">
        {script.title ?? "Untitled script"}
      </div>
      {script.hook && (
        <div className="text-[12.5px] text-muted mt-2 leading-relaxed line-clamp-3">
          {script.hook}
        </div>
      )}
      <div className="flex items-center justify-between mt-3 pt-3 border-t border-border">
        <span className="text-[11px] text-muted inline-flex items-center gap-1">
          {script.status === "draft" && <PencilLine className="w-3 h-3" />}
          {script.status === "approved" && <CheckCircle2 className="w-3 h-3 text-accent" />}
          {script.status === "used" && <CheckCircle2 className="w-3 h-3 text-emerald-600" />}
          {script.status === "archived" && <Archive className="w-3 h-3" />}
          {timeAgo(script.created_at)}
        </span>
        <ArrowRight className="w-3.5 h-3.5 text-muted" />
      </div>
    </button>
  );
}

function timeAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const min = Math.round(ms / 60000);
  if (min < 1) return "just now";
  if (min < 60) return `${min}m ago`;
  const hr = Math.round(min / 60);
  if (hr < 24) return `${hr}h ago`;
  const day = Math.round(hr / 24);
  if (day < 30) return `${day}d ago`;
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

