/**
 * Generated by `mcp__supabase__generate_typescript_types` against the
 * linked cloud project (wfyhsohnkbzemwxuiqhr) at schema version 18.
 *
 * Regenerate via `npm run db:types` after applying a migration.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      assets: {
        Row: {
          aesthetic_score: number | null
          created_at: string
          duration_seconds: number | null
          id: string
          kind: Database["public"]["Enums"]["asset_kind_t"]
          mood: string | null
          scene: string | null
          source: string
          storage_key: string
          tags: string[]
          thumbnail_storage_key: string | null
          title: string
          transcoded_variants: Json | null
          updated_at: string
          user_id: string
        }
        Insert: {
          aesthetic_score?: number | null
          created_at?: string
          duration_seconds?: number | null
          id?: string
          kind: Database["public"]["Enums"]["asset_kind_t"]
          mood?: string | null
          scene?: string | null
          source?: string
          storage_key: string
          tags?: string[]
          thumbnail_storage_key?: string | null
          title: string
          transcoded_variants?: Json | null
          updated_at?: string
          user_id: string
        }
        Update: {
          aesthetic_score?: number | null
          created_at?: string
          duration_seconds?: number | null
          id?: string
          kind?: Database["public"]["Enums"]["asset_kind_t"]
          mood?: string | null
          scene?: string | null
          source?: string
          storage_key?: string
          tags?: string[]
          thumbnail_storage_key?: string | null
          title?: string
          transcoded_variants?: Json | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "assets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor: string
          at: string
          id: string
          ip: unknown
          metadata: Json | null
          target_id: string | null
          target_type: string | null
          user_agent: string | null
          user_id: string
        }
        Insert: {
          action: string
          actor: string
          at?: string
          id?: string
          ip?: unknown
          metadata?: Json | null
          target_id?: string | null
          target_type?: string | null
          user_agent?: string | null
          user_id: string
        }
        Update: {
          action?: string
          actor?: string
          at?: string
          id?: string
          ip?: unknown
          metadata?: Json | null
          target_id?: string | null
          target_type?: string | null
          user_agent?: string | null
          user_id?: string
        }
        Relationships: []
      }
      content_analyses: {
        Row: {
          created_at: string
          hook: string | null
          id: string
          source_creator: string | null
          source_platform: Database["public"]["Enums"]["source_platform_t"]
          source_thumbnail: string | null
          source_title: string | null
          source_url: string
          status: Database["public"]["Enums"]["analysis_status_t"]
          structure: Json | null
          transcription: string | null
          updated_at: string
          user_id: string
          variations: Json | null
          why_it_worked: Json | null
        }
        Insert: {
          created_at?: string
          hook?: string | null
          id?: string
          source_creator?: string | null
          source_platform: Database["public"]["Enums"]["source_platform_t"]
          source_thumbnail?: string | null
          source_title?: string | null
          source_url: string
          status?: Database["public"]["Enums"]["analysis_status_t"]
          structure?: Json | null
          transcription?: string | null
          updated_at?: string
          user_id: string
          variations?: Json | null
          why_it_worked?: Json | null
        }
        Update: {
          created_at?: string
          hook?: string | null
          id?: string
          source_creator?: string | null
          source_platform?: Database["public"]["Enums"]["source_platform_t"]
          source_thumbnail?: string | null
          source_title?: string | null
          source_url?: string
          status?: Database["public"]["Enums"]["analysis_status_t"]
          structure?: Json | null
          transcription?: string | null
          updated_at?: string
          user_id?: string
          variations?: Json | null
          why_it_worked?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "content_analyses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      content_drafts: {
        Row: {
          analysis_id: string
          angle: string | null
          audience: string | null
          captions: Json | null
          created_at: string
          hooks: Json | null
          id: string
          script: string | null
          shots: Json | null
          target_platform: string | null
          tone: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          analysis_id: string
          angle?: string | null
          audience?: string | null
          captions?: Json | null
          created_at?: string
          hooks?: Json | null
          id?: string
          script?: string | null
          shots?: Json | null
          target_platform?: string | null
          tone?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          analysis_id?: string
          angle?: string | null
          audience?: string | null
          captions?: Json | null
          created_at?: string
          hooks?: Json | null
          id?: string
          script?: string | null
          shots?: Json | null
          target_platform?: string | null
          tone?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "content_drafts_analysis_id_fkey"
            columns: ["analysis_id"]
            isOneToOne: false
            referencedRelation: "content_analyses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_drafts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      creator_relationships: {
        Row: {
          accepted_at: string | null
          created_at: string
          creator_id: string | null
          ended_at: string | null
          expires_at: string
          id: string
          invite_token: string | null
          invited_email: string | null
          manager_id: string
          status: Database["public"]["Enums"]["relationship_status_t"]
          updated_at: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          creator_id?: string | null
          ended_at?: string | null
          expires_at?: string
          id?: string
          invite_token?: string | null
          invited_email?: string | null
          manager_id: string
          status?: Database["public"]["Enums"]["relationship_status_t"]
          updated_at?: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          creator_id?: string | null
          ended_at?: string | null
          expires_at?: string
          id?: string
          invite_token?: string | null
          invited_email?: string | null
          manager_id?: string
          status?: Database["public"]["Enums"]["relationship_status_t"]
          updated_at?: string
        }
        Relationships: []
      }
      deletion_requests: {
        Row: {
          completed_at: string | null
          confirmation_code: string
          id: string
          reason: string | null
          requested_at: string
          source: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          confirmation_code: string
          id?: string
          reason?: string | null
          requested_at?: string
          source: string
          user_id: string
        }
        Update: {
          completed_at?: string | null
          confirmation_code?: string
          id?: string
          reason?: string | null
          requested_at?: string
          source?: string
          user_id?: string
        }
        Relationships: []
      }
      integrations: {
        Row: {
          access_token_ciphertext: string
          access_token_dek: string
          access_token_key_id: string
          account_type: string | null
          connected_at: string
          disconnected_at: string | null
          external_account_id: string
          id: string
          last_synced_at: string | null
          platform: Database["public"]["Enums"]["platform_t"]
          refresh_token_ciphertext: string | null
          refresh_token_dek: string | null
          refresh_token_key_id: string | null
          scopes: string[]
          status: Database["public"]["Enums"]["integration_status_t"]
          token_expires_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          access_token_ciphertext: string
          access_token_dek: string
          access_token_key_id: string
          account_type?: string | null
          connected_at?: string
          disconnected_at?: string | null
          external_account_id: string
          id?: string
          last_synced_at?: string | null
          platform: Database["public"]["Enums"]["platform_t"]
          refresh_token_ciphertext?: string | null
          refresh_token_dek?: string | null
          refresh_token_key_id?: string | null
          scopes?: string[]
          status?: Database["public"]["Enums"]["integration_status_t"]
          token_expires_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          access_token_ciphertext?: string
          access_token_dek?: string
          access_token_key_id?: string
          account_type?: string | null
          connected_at?: string
          disconnected_at?: string | null
          external_account_id?: string
          id?: string
          last_synced_at?: string | null
          platform?: Database["public"]["Enums"]["platform_t"]
          refresh_token_ciphertext?: string | null
          refresh_token_dek?: string | null
          refresh_token_key_id?: string | null
          scopes?: string[]
          status?: Database["public"]["Enums"]["integration_status_t"]
          token_expires_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      jobs: {
        Row: {
          asset_id: string | null
          attempts: number
          claimed_at: string | null
          created_at: string
          cursor: Json | null
          error_text: string | null
          finished_at: string | null
          heartbeat_at: string | null
          id: string
          integration_id: string | null
          kind: Database["public"]["Enums"]["job_kind_t"]
          max_attempts: number
          next_attempt_at: string
          payload: Json
          post_id: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["job_status_t"]
          sub_type: string | null
          user_id: string
        }
        Insert: {
          asset_id?: string | null
          attempts?: number
          claimed_at?: string | null
          created_at?: string
          cursor?: Json | null
          error_text?: string | null
          finished_at?: string | null
          heartbeat_at?: string | null
          id?: string
          integration_id?: string | null
          kind: Database["public"]["Enums"]["job_kind_t"]
          max_attempts?: number
          next_attempt_at?: string
          payload?: Json
          post_id?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["job_status_t"]
          sub_type?: string | null
          user_id: string
        }
        Update: {
          asset_id?: string | null
          attempts?: number
          claimed_at?: string | null
          created_at?: string
          cursor?: Json | null
          error_text?: string | null
          finished_at?: string | null
          heartbeat_at?: string | null
          id?: string
          integration_id?: string | null
          kind?: Database["public"]["Enums"]["job_kind_t"]
          max_attempts?: number
          next_attempt_at?: string
          payload?: Json
          post_id?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["job_status_t"]
          sub_type?: string | null
          user_id?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["notification_kind_t"]
          read_at: string | null
          recipient_id: string
          target_id: string | null
          target_type: string | null
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          kind: Database["public"]["Enums"]["notification_kind_t"]
          read_at?: string | null
          recipient_id: string
          target_id?: string | null
          target_type?: string | null
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["notification_kind_t"]
          read_at?: string | null
          recipient_id?: string
          target_id?: string | null
          target_type?: string | null
        }
        Relationships: []
      }
      oauth_states: {
        Row: {
          code_verifier_hash: string | null
          consumed_at: string | null
          created_at: string
          expires_at: string
          platform: Database["public"]["Enums"]["platform_t"]
          redirect_uri: string
          state: string
          user_id: string
        }
        Insert: {
          code_verifier_hash?: string | null
          consumed_at?: string | null
          created_at?: string
          expires_at: string
          platform: Database["public"]["Enums"]["platform_t"]
          redirect_uri: string
          state: string
          user_id: string
        }
        Update: {
          code_verifier_hash?: string | null
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          platform?: Database["public"]["Enums"]["platform_t"]
          redirect_uri?: string
          state?: string
          user_id?: string
        }
        Relationships: []
      }
      posts: {
        Row: {
          caption: string | null
          comments: number | null
          created_at: string
          engagement_rate: number | null
          external_id: string | null
          id: string
          imported_at: string | null
          integration_id: string | null
          last_insight_sync_at: string | null
          lifecycle_state: Database["public"]["Enums"]["post_lifecycle_t"]
          likes: number | null
          platform: Database["public"]["Enums"]["platform_t"]
          publish_error: string | null
          published_at: string | null
          reach: number | null
          saves: number | null
          scheduled_at: string | null
          scheduled_at_timezone: string | null
          shares: number | null
          source: Database["public"]["Enums"]["post_source_t"]
          thumbnail_url: string | null
          type: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          caption?: string | null
          comments?: number | null
          created_at?: string
          engagement_rate?: number | null
          external_id?: string | null
          id?: string
          imported_at?: string | null
          integration_id?: string | null
          last_insight_sync_at?: string | null
          lifecycle_state: Database["public"]["Enums"]["post_lifecycle_t"]
          likes?: number | null
          platform: Database["public"]["Enums"]["platform_t"]
          publish_error?: string | null
          published_at?: string | null
          reach?: number | null
          saves?: number | null
          scheduled_at?: string | null
          scheduled_at_timezone?: string | null
          shares?: number | null
          source: Database["public"]["Enums"]["post_source_t"]
          thumbnail_url?: string | null
          type?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          caption?: string | null
          comments?: number | null
          created_at?: string
          engagement_rate?: number | null
          external_id?: string | null
          id?: string
          imported_at?: string | null
          integration_id?: string | null
          last_insight_sync_at?: string | null
          lifecycle_state?: Database["public"]["Enums"]["post_lifecycle_t"]
          likes?: number | null
          platform?: Database["public"]["Enums"]["platform_t"]
          publish_error?: string | null
          published_at?: string | null
          reach?: number | null
          saves?: number | null
          scheduled_at?: string | null
          scheduled_at_timezone?: string | null
          shares?: number | null
          source?: Database["public"]["Enums"]["post_source_t"]
          thumbnail_url?: string | null
          type?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          asset_types: string[]
          audience_problem: string | null
          audience_wants: string | null
          audience_who: string | null
          avatar_url: string | null
          biggest_problem: string | null
          brand_tones: string[]
          completed_at: string | null
          content_formats: string[]
          created_at: string
          creator_type: string
          cta_style: string | null
          custom_cta: string | null
          display_name: string | null
          email_notifications: boolean
          frequency: string | null
          handle: string | null
          niche: string
          offer_name: string | null
          planning_workflow: string[]
          platforms: string[]
          primary_goal: string
          reports_needs: string[]
          schema_version: number
          secondary_goals: string[]
          selling: string[]
          sequence_uses: string[]
          start_mode: string
          stripe_customer_id: string | null
          team: string | null
          timezone: string
          trial_cycle: string | null
          trial_expires_at: string | null
          trial_plan: string | null
          trial_started_at: string | null
          updated_at: string
          user_id: string
          wants_niche_presets: boolean
        }
        Insert: {
          asset_types?: string[]
          audience_problem?: string | null
          audience_wants?: string | null
          audience_who?: string | null
          avatar_url?: string | null
          biggest_problem?: string | null
          brand_tones?: string[]
          completed_at?: string | null
          content_formats?: string[]
          created_at?: string
          creator_type: string
          cta_style?: string | null
          custom_cta?: string | null
          display_name?: string | null
          email_notifications?: boolean
          frequency?: string | null
          handle?: string | null
          niche: string
          offer_name?: string | null
          planning_workflow?: string[]
          platforms?: string[]
          primary_goal: string
          reports_needs?: string[]
          schema_version?: number
          secondary_goals?: string[]
          selling?: string[]
          sequence_uses?: string[]
          start_mode?: string
          stripe_customer_id?: string | null
          team?: string | null
          timezone?: string
          trial_cycle?: string | null
          trial_expires_at?: string | null
          trial_plan?: string | null
          trial_started_at?: string | null
          updated_at?: string
          user_id: string
          wants_niche_presets?: boolean
        }
        Update: {
          asset_types?: string[]
          audience_problem?: string | null
          audience_wants?: string | null
          audience_who?: string | null
          avatar_url?: string | null
          biggest_problem?: string | null
          brand_tones?: string[]
          completed_at?: string | null
          content_formats?: string[]
          created_at?: string
          creator_type?: string
          cta_style?: string | null
          custom_cta?: string | null
          display_name?: string | null
          email_notifications?: boolean
          frequency?: string | null
          handle?: string | null
          niche?: string
          offer_name?: string | null
          planning_workflow?: string[]
          platforms?: string[]
          primary_goal?: string
          reports_needs?: string[]
          schema_version?: number
          secondary_goals?: string[]
          selling?: string[]
          sequence_uses?: string[]
          start_mode?: string
          stripe_customer_id?: string | null
          team?: string | null
          timezone?: string
          trial_cycle?: string | null
          trial_expires_at?: string | null
          trial_plan?: string | null
          trial_started_at?: string | null
          updated_at?: string
          user_id?: string
          wants_niche_presets?: boolean
        }
        Relationships: []
      }
      relationship_documents: {
        Row: {
          asset_id: string
          created_at: string
          id: string
          relationship_id: string
          shared_by: string
        }
        Insert: {
          asset_id: string
          created_at?: string
          id?: string
          relationship_id: string
          shared_by: string
        }
        Update: {
          asset_id?: string
          created_at?: string
          id?: string
          relationship_id?: string
          shared_by?: string
        }
        Relationships: []
      }
      relationship_links: {
        Row: {
          added_by: string
          created_at: string
          description: string | null
          id: string
          relationship_id: string
          title: string | null
          url: string
        }
        Insert: {
          added_by: string
          created_at?: string
          description?: string | null
          id?: string
          relationship_id: string
          title?: string | null
          url: string
        }
        Update: {
          added_by?: string
          created_at?: string
          description?: string | null
          id?: string
          relationship_id?: string
          title?: string | null
          url?: string
        }
        Relationships: []
      }
      relationship_messages: {
        Row: {
          body: string
          created_at: string
          id: string
          read_at: string | null
          relationship_id: string
          sender_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          read_at?: string | null
          relationship_id: string
          sender_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          read_at?: string | null
          relationship_id?: string
          sender_id?: string
        }
        Relationships: []
      }
      relationship_task_completions: {
        Row: {
          completed_at: string
          day: string
          task_id: string
        }
        Insert: {
          completed_at?: string
          day: string
          task_id: string
        }
        Update: {
          completed_at?: string
          day?: string
          task_id?: string
        }
        Relationships: []
      }
      relationship_tasks: {
        Row: {
          assigned_to: string
          completed_at: string | null
          created_at: string
          created_by: string
          creator_note: string | null
          deadline: string | null
          ended_at: string | null
          id: string
          notes: string | null
          recurrence: Database["public"]["Enums"]["task_recurrence_t"]
          relationship_id: string
          status: Database["public"]["Enums"]["task_status_t"]
          title: string
          updated_at: string
        }
        Insert: {
          assigned_to: string
          completed_at?: string | null
          created_at?: string
          created_by: string
          creator_note?: string | null
          deadline?: string | null
          ended_at?: string | null
          id?: string
          notes?: string | null
          recurrence?: Database["public"]["Enums"]["task_recurrence_t"]
          relationship_id: string
          status?: Database["public"]["Enums"]["task_status_t"]
          title: string
          updated_at?: string
        }
        Update: {
          assigned_to?: string
          completed_at?: string | null
          created_at?: string
          created_by?: string
          creator_note?: string | null
          deadline?: string | null
          ended_at?: string | null
          id?: string
          notes?: string | null
          recurrence?: Database["public"]["Enums"]["task_recurrence_t"]
          relationship_id?: string
          status?: Database["public"]["Enums"]["task_status_t"]
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      schema_migrations: {
        Row: {
          applied_at: string
          checksum: string | null
          version: number
        }
        Insert: {
          applied_at?: string
          checksum?: string | null
          version: number
        }
        Update: {
          applied_at?: string
          checksum?: string | null
          version?: number
        }
        Relationships: []
      }
      sequences: {
        Row: {
          accent_color: string | null
          brand_tone: string | null
          brief: string | null
          content_style: string | null
          created_at: string
          decorations: string[]
          goal: string | null
          id: string
          persona: string | null
          published_at: string | null
          scheduled_at: string | null
          scheduled_at_timezone: string | null
          slides: Json
          status: string
          title: string
          updated_at: string
          user_id: string
          version: number
        }
        Insert: {
          accent_color?: string | null
          brand_tone?: string | null
          brief?: string | null
          content_style?: string | null
          created_at?: string
          decorations?: string[]
          goal?: string | null
          id?: string
          persona?: string | null
          published_at?: string | null
          scheduled_at?: string | null
          scheduled_at_timezone?: string | null
          slides?: Json
          status?: string
          title: string
          updated_at?: string
          user_id: string
          version?: number
        }
        Update: {
          accent_color?: string | null
          brand_tone?: string | null
          brief?: string | null
          content_style?: string | null
          created_at?: string
          decorations?: string[]
          goal?: string | null
          id?: string
          persona?: string | null
          published_at?: string | null
          scheduled_at?: string | null
          scheduled_at_timezone?: string | null
          slides?: Json
          status?: string
          title?: string
          updated_at?: string
          user_id?: string
          version?: number
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean
          created_at: string
          current_period_end: string | null
          cycle: string
          id: string
          plan: string
          status: Database["public"]["Enums"]["subscription_status_t"]
          stripe_customer_id: string
          stripe_subscription_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          cycle: string
          id?: string
          plan: string
          status: Database["public"]["Enums"]["subscription_status_t"]
          stripe_customer_id: string
          stripe_subscription_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          cycle?: string
          id?: string
          plan?: string
          status?: Database["public"]["Enums"]["subscription_status_t"]
          stripe_customer_id?: string
          stripe_subscription_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      sync_runs: {
        Row: {
          cursor: Json | null
          error_text: string | null
          finished_at: string | null
          id: string
          integration_id: string
          job_id: string | null
          pages_fetched: number | null
          posts_upserted: number | null
          started_at: string
          status: string
        }
        Insert: {
          cursor?: Json | null
          error_text?: string | null
          finished_at?: string | null
          id?: string
          integration_id: string
          job_id?: string | null
          pages_fetched?: number | null
          posts_upserted?: number | null
          started_at?: string
          status: string
        }
        Update: {
          cursor?: Json | null
          error_text?: string | null
          finished_at?: string | null
          id?: string
          integration_id?: string
          job_id?: string | null
          pages_fetched?: number | null
          posts_upserted?: number | null
          started_at?: string
          status?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          deleted_at: string | null
          display_name: string | null
          email: string
          handle: string | null
          id: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          display_name?: string | null
          email: string
          handle?: string | null
          id: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          display_name?: string | null
          email?: string
          handle?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
      webhook_events: {
        Row: {
          external_id: string
          id: string
          payload: Json
          process_error: string | null
          processed_at: string | null
          provider: Database["public"]["Enums"]["platform_t"]
          received_at: string
          signature_verified: boolean
        }
        Insert: {
          external_id: string
          id?: string
          payload: Json
          process_error?: string | null
          processed_at?: string | null
          provider: Database["public"]["Enums"]["platform_t"]
          received_at?: string
          signature_verified: boolean
        }
        Update: {
          external_id?: string
          id?: string
          payload?: Json
          process_error?: string | null
          processed_at?: string | null
          provider?: Database["public"]["Enums"]["platform_t"]
          received_at?: string
          signature_verified?: boolean
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_relationship_member: { Args: { rel_id: string }; Returns: boolean }
    }
    Enums: {
      analysis_status_t: "analyzing" | "ready" | "failed"
      asset_kind_t: "photo" | "video" | "screenshot" | "testimonial" | "proof"
      integration_status_t: "active" | "expired" | "revoked" | "unsupported"
      job_kind_t:
        | "sync"
        | "transcode"
        | "publish"
        | "refresh_token"
        | "finalize_deletion"
        | "cleanup"
        | "content_dna_analyze"
      job_status_t: "queued" | "running" | "completed" | "failed" | "dead"
      notification_kind_t:
        | "invite"
        | "message"
        | "task_assigned"
        | "task_due"
        | "streak_at_risk"
      platform_t:
        | "instagram"
        | "tiktok"
        | "youtube"
        | "linkedin"
        | "x"
        | "facebook"
      post_lifecycle_t:
        | "draft"
        | "review"
        | "scheduled"
        | "publishing"
        | "published"
        | "failed"
        | "analyzed"
      post_source_t: "imported" | "native"
      relationship_status_t:
        | "pending"
        | "active"
        | "declined"
        | "ended"
        | "expired"
      source_platform_t: "youtube" | "instagram" | "tiktok" | "other"
      subscription_status_t:
        | "trialing"
        | "active"
        | "past_due"
        | "canceled"
        | "incomplete"
        | "incomplete_expired"
        | "unpaid"
        | "paused"
      task_recurrence_t: "none" | "daily"
      task_status_t: "pending" | "in_progress" | "done"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      analysis_status_t: ["analyzing", "ready", "failed"],
      asset_kind_t: ["photo", "video", "screenshot", "testimonial", "proof"],
      integration_status_t: ["active", "expired", "revoked", "unsupported"],
      job_kind_t: [
        "sync",
        "transcode",
        "publish",
        "refresh_token",
        "finalize_deletion",
        "cleanup",
        "content_dna_analyze",
      ],
      job_status_t: ["queued", "running", "completed", "failed", "dead"],
      notification_kind_t: [
        "invite",
        "message",
        "task_assigned",
        "task_due",
        "streak_at_risk",
      ],
      platform_t: [
        "instagram",
        "tiktok",
        "youtube",
        "linkedin",
        "x",
        "facebook",
      ],
      post_lifecycle_t: [
        "draft",
        "review",
        "scheduled",
        "publishing",
        "published",
        "failed",
        "analyzed",
      ],
      post_source_t: ["imported", "native"],
      relationship_status_t: [
        "pending",
        "active",
        "declined",
        "ended",
        "expired",
      ],
      source_platform_t: ["youtube", "instagram", "tiktok", "other"],
      subscription_status_t: [
        "trialing",
        "active",
        "past_due",
        "canceled",
        "incomplete",
        "incomplete_expired",
        "unpaid",
        "paused",
      ],
      task_recurrence_t: ["none", "daily"],
      task_status_t: ["pending", "in_progress", "done"],
    },
  },
} as const
