/**
 * Generated by `mcp__supabase__generate_typescript_types` against the
 * linked cloud project (wfyhsohnkbzemwxuiqhr) at schema version 12.
 *
 * Regenerate via `npm run db:types` after applying a migration.
 * Drift is caught by the migration round-trip CI test.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      assets: {
        Row: {
          aesthetic_score: number | null
          created_at: string
          duration_seconds: number | null
          id: string
          kind: Database["public"]["Enums"]["asset_kind_t"]
          mood: string | null
          scene: string | null
          source: string
          storage_key: string
          tags: string[]
          thumbnail_storage_key: string | null
          title: string
          transcoded_variants: Json | null
          updated_at: string
          user_id: string
        }
        Insert: {
          aesthetic_score?: number | null
          created_at?: string
          duration_seconds?: number | null
          id?: string
          kind: Database["public"]["Enums"]["asset_kind_t"]
          mood?: string | null
          scene?: string | null
          source?: string
          storage_key: string
          tags?: string[]
          thumbnail_storage_key?: string | null
          title: string
          transcoded_variants?: Json | null
          updated_at?: string
          user_id: string
        }
        Update: {
          aesthetic_score?: number | null
          created_at?: string
          duration_seconds?: number | null
          id?: string
          kind?: Database["public"]["Enums"]["asset_kind_t"]
          mood?: string | null
          scene?: string | null
          source?: string
          storage_key?: string
          tags?: string[]
          thumbnail_storage_key?: string | null
          title?: string
          transcoded_variants?: Json | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "assets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor: string
          at: string
          id: string
          ip: unknown
          metadata: Json | null
          target_id: string | null
          target_type: string | null
          user_agent: string | null
          user_id: string
        }
        Insert: {
          action: string
          actor: string
          at?: string
          id?: string
          ip?: unknown
          metadata?: Json | null
          target_id?: string | null
          target_type?: string | null
          user_agent?: string | null
          user_id: string
        }
        Update: {
          action?: string
          actor?: string
          at?: string
          id?: string
          ip?: unknown
          metadata?: Json | null
          target_id?: string | null
          target_type?: string | null
          user_agent?: string | null
          user_id?: string
        }
        Relationships: []
      }
      deletion_requests: {
        Row: {
          completed_at: string | null
          confirmation_code: string
          id: string
          reason: string | null
          requested_at: string
          source: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          confirmation_code: string
          id?: string
          reason?: string | null
          requested_at?: string
          source: string
          user_id: string
        }
        Update: {
          completed_at?: string | null
          confirmation_code?: string
          id?: string
          reason?: string | null
          requested_at?: string
          source?: string
          user_id?: string
        }
        Relationships: []
      }
      integrations: {
        Row: {
          access_token_ciphertext: string
          access_token_dek: string
          access_token_key_id: string
          account_type: string | null
          connected_at: string
          disconnected_at: string | null
          external_account_id: string
          id: string
          last_synced_at: string | null
          platform: Database["public"]["Enums"]["platform_t"]
          refresh_token_ciphertext: string | null
          refresh_token_dek: string | null
          refresh_token_key_id: string | null
          scopes: string[]
          status: Database["public"]["Enums"]["integration_status_t"]
          token_expires_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          access_token_ciphertext: string
          access_token_dek: string
          access_token_key_id: string
          account_type?: string | null
          connected_at?: string
          disconnected_at?: string | null
          external_account_id: string
          id?: string
          last_synced_at?: string | null
          platform: Database["public"]["Enums"]["platform_t"]
          refresh_token_ciphertext?: string | null
          refresh_token_dek?: string | null
          refresh_token_key_id?: string | null
          scopes?: string[]
          status?: Database["public"]["Enums"]["integration_status_t"]
          token_expires_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          access_token_ciphertext?: string
          access_token_dek?: string
          access_token_key_id?: string
          account_type?: string | null
          connected_at?: string
          disconnected_at?: string | null
          external_account_id?: string
          id?: string
          last_synced_at?: string | null
          platform?: Database["public"]["Enums"]["platform_t"]
          refresh_token_ciphertext?: string | null
          refresh_token_dek?: string | null
          refresh_token_key_id?: string | null
          scopes?: string[]
          status?: Database["public"]["Enums"]["integration_status_t"]
          token_expires_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "integrations_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          asset_id: string | null
          attempts: number
          claimed_at: string | null
          created_at: string
          cursor: Json | null
          error_text: string | null
          finished_at: string | null
          heartbeat_at: string | null
          id: string
          integration_id: string | null
          kind: Database["public"]["Enums"]["job_kind_t"]
          max_attempts: number
          next_attempt_at: string
          payload: Json
          post_id: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["job_status_t"]
          sub_type: string | null
          user_id: string
        }
        Insert: {
          asset_id?: string | null
          attempts?: number
          claimed_at?: string | null
          created_at?: string
          cursor?: Json | null
          error_text?: string | null
          finished_at?: string | null
          heartbeat_at?: string | null
          id?: string
          integration_id?: string | null
          kind: Database["public"]["Enums"]["job_kind_t"]
          max_attempts?: number
          next_attempt_at?: string
          payload?: Json
          post_id?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["job_status_t"]
          sub_type?: string | null
          user_id: string
        }
        Update: {
          asset_id?: string | null
          attempts?: number
          claimed_at?: string | null
          created_at?: string
          cursor?: Json | null
          error_text?: string | null
          finished_at?: string | null
          heartbeat_at?: string | null
          id?: string
          integration_id?: string | null
          kind?: Database["public"]["Enums"]["job_kind_t"]
          max_attempts?: number
          next_attempt_at?: string
          payload?: Json
          post_id?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["job_status_t"]
          sub_type?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_asset_id_fkey"
            columns: ["asset_id"]
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_integration_id_fkey"
            columns: ["integration_id"]
            isOneToOne: false
            referencedRelation: "integrations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
        ]
      }
      oauth_states: {
        Row: {
          code_verifier_hash: string | null
          consumed_at: string | null
          created_at: string
          expires_at: string
          platform: Database["public"]["Enums"]["platform_t"]
          redirect_uri: string
          state: string
          user_id: string
        }
        Insert: {
          code_verifier_hash?: string | null
          consumed_at?: string | null
          created_at?: string
          expires_at: string
          platform: Database["public"]["Enums"]["platform_t"]
          redirect_uri: string
          state: string
          user_id: string
        }
        Update: {
          code_verifier_hash?: string | null
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          platform?: Database["public"]["Enums"]["platform_t"]
          redirect_uri?: string
          state?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "oauth_states_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      posts: {
        Row: {
          caption: string | null
          comments: number | null
          created_at: string
          engagement_rate: number | null
          external_id: string | null
          id: string
          imported_at: string | null
          integration_id: string | null
          last_insight_sync_at: string | null
          lifecycle_state: Database["public"]["Enums"]["post_lifecycle_t"]
          likes: number | null
          platform: Database["public"]["Enums"]["platform_t"]
          publish_error: string | null
          published_at: string | null
          reach: number | null
          saves: number | null
          scheduled_at: string | null
          scheduled_at_timezone: string | null
          shares: number | null
          source: Database["public"]["Enums"]["post_source_t"]
          thumbnail_url: string | null
          type: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          caption?: string | null
          comments?: number | null
          created_at?: string
          engagement_rate?: number | null
          external_id?: string | null
          id?: string
          imported_at?: string | null
          integration_id?: string | null
          last_insight_sync_at?: string | null
          lifecycle_state: Database["public"]["Enums"]["post_lifecycle_t"]
          likes?: number | null
          platform: Database["public"]["Enums"]["platform_t"]
          publish_error?: string | null
          published_at?: string | null
          reach?: number | null
          saves?: number | null
          scheduled_at?: string | null
          scheduled_at_timezone?: string | null
          shares?: number | null
          source: Database["public"]["Enums"]["post_source_t"]
          thumbnail_url?: string | null
          type?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          caption?: string | null
          comments?: number | null
          created_at?: string
          engagement_rate?: number | null
          external_id?: string | null
          id?: string
          imported_at?: string | null
          integration_id?: string | null
          last_insight_sync_at?: string | null
          lifecycle_state?: Database["public"]["Enums"]["post_lifecycle_t"]
          likes?: number | null
          platform?: Database["public"]["Enums"]["platform_t"]
          publish_error?: string | null
          published_at?: string | null
          reach?: number | null
          saves?: number | null
          scheduled_at?: string | null
          scheduled_at_timezone?: string | null
          shares?: number | null
          source?: Database["public"]["Enums"]["post_source_t"]
          thumbnail_url?: string | null
          type?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "posts_integration_id_fkey"
            columns: ["integration_id"]
            isOneToOne: false
            referencedRelation: "integrations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          asset_types: string[]
          audience_problem: string | null
          audience_wants: string | null
          audience_who: string | null
          avatar_url: string | null
          biggest_problem: string | null
          brand_tones: string[]
          completed_at: string | null
          content_formats: string[]
          created_at: string
          creator_type: string
          cta_style: string | null
          custom_cta: string | null
          display_name: string | null
          frequency: string | null
          handle: string | null
          niche: string
          offer_name: string | null
          planning_workflow: string[]
          platforms: string[]
          primary_goal: string
          reports_needs: string[]
          schema_version: number
          secondary_goals: string[]
          selling: string[]
          sequence_uses: string[]
          start_mode: string
          team: string | null
          timezone: string
          updated_at: string
          user_id: string
          wants_niche_presets: boolean
        }
        Insert: {
          asset_types?: string[]
          audience_problem?: string | null
          audience_wants?: string | null
          audience_who?: string | null
          avatar_url?: string | null
          biggest_problem?: string | null
          brand_tones?: string[]
          completed_at?: string | null
          content_formats?: string[]
          created_at?: string
          creator_type: string
          cta_style?: string | null
          custom_cta?: string | null
          display_name?: string | null
          frequency?: string | null
          handle?: string | null
          niche: string
          offer_name?: string | null
          planning_workflow?: string[]
          platforms?: string[]
          primary_goal: string
          reports_needs?: string[]
          schema_version?: number
          secondary_goals?: string[]
          selling?: string[]
          sequence_uses?: string[]
          start_mode?: string
          team?: string | null
          timezone?: string
          updated_at?: string
          user_id: string
          wants_niche_presets?: boolean
        }
        Update: {
          asset_types?: string[]
          audience_problem?: string | null
          audience_wants?: string | null
          audience_who?: string | null
          avatar_url?: string | null
          biggest_problem?: string | null
          brand_tones?: string[]
          completed_at?: string | null
          content_formats?: string[]
          created_at?: string
          creator_type?: string
          cta_style?: string | null
          custom_cta?: string | null
          display_name?: string | null
          frequency?: string | null
          handle?: string | null
          niche?: string
          offer_name?: string | null
          planning_workflow?: string[]
          platforms?: string[]
          primary_goal?: string
          reports_needs?: string[]
          schema_version?: number
          secondary_goals?: string[]
          selling?: string[]
          sequence_uses?: string[]
          start_mode?: string
          team?: string | null
          timezone?: string
          updated_at?: string
          user_id?: string
          wants_niche_presets?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      schema_migrations: {
        Row: {
          applied_at: string
          checksum: string | null
          version: number
        }
        Insert: {
          applied_at?: string
          checksum?: string | null
          version: number
        }
        Update: {
          applied_at?: string
          checksum?: string | null
          version?: number
        }
        Relationships: []
      }
      sequences: {
        Row: {
          accent_color: string | null
          brand_tone: string | null
          brief: string | null
          content_style: string | null
          created_at: string
          decorations: string[]
          goal: string | null
          id: string
          persona: string | null
          published_at: string | null
          scheduled_at: string | null
          scheduled_at_timezone: string | null
          slides: Json
          status: string
          title: string
          updated_at: string
          user_id: string
          version: number
        }
        Insert: {
          accent_color?: string | null
          brand_tone?: string | null
          brief?: string | null
          content_style?: string | null
          created_at?: string
          decorations?: string[]
          goal?: string | null
          id?: string
          persona?: string | null
          published_at?: string | null
          scheduled_at?: string | null
          scheduled_at_timezone?: string | null
          slides?: Json
          status?: string
          title: string
          updated_at?: string
          user_id: string
          version?: number
        }
        Update: {
          accent_color?: string | null
          brand_tone?: string | null
          brief?: string | null
          content_style?: string | null
          created_at?: string
          decorations?: string[]
          goal?: string | null
          id?: string
          persona?: string | null
          published_at?: string | null
          scheduled_at?: string | null
          scheduled_at_timezone?: string | null
          slides?: Json
          status?: string
          title?: string
          updated_at?: string
          user_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "sequences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      sync_runs: {
        Row: {
          cursor: Json | null
          error_text: string | null
          finished_at: string | null
          id: string
          integration_id: string
          job_id: string | null
          pages_fetched: number | null
          posts_upserted: number | null
          started_at: string
          status: string
        }
        Insert: {
          cursor?: Json | null
          error_text?: string | null
          finished_at?: string | null
          id?: string
          integration_id: string
          job_id?: string | null
          pages_fetched?: number | null
          posts_upserted?: number | null
          started_at?: string
          status: string
        }
        Update: {
          cursor?: Json | null
          error_text?: string | null
          finished_at?: string | null
          id?: string
          integration_id?: string
          job_id?: string | null
          pages_fetched?: number | null
          posts_upserted?: number | null
          started_at?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "sync_runs_integration_id_fkey"
            columns: ["integration_id"]
            isOneToOne: false
            referencedRelation: "integrations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sync_runs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          deleted_at: string | null
          display_name: string | null
          email: string
          handle: string | null
          id: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          display_name?: string | null
          email: string
          handle?: string | null
          id: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          display_name?: string | null
          email?: string
          handle?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
      webhook_events: {
        Row: {
          external_id: string
          id: string
          payload: Json
          process_error: string | null
          processed_at: string | null
          provider: Database["public"]["Enums"]["platform_t"]
          received_at: string
          signature_verified: boolean
        }
        Insert: {
          external_id: string
          id?: string
          payload: Json
          process_error?: string | null
          processed_at?: string | null
          provider: Database["public"]["Enums"]["platform_t"]
          received_at?: string
          signature_verified: boolean
        }
        Update: {
          external_id?: string
          id?: string
          payload?: Json
          process_error?: string | null
          processed_at?: string | null
          provider?: Database["public"]["Enums"]["platform_t"]
          received_at?: string
          signature_verified?: boolean
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      asset_kind_t: "photo" | "video" | "screenshot" | "testimonial" | "proof"
      integration_status_t: "active" | "expired" | "revoked" | "unsupported"
      job_kind_t:
        | "sync"
        | "transcode"
        | "publish"
        | "refresh_token"
        | "finalize_deletion"
        | "cleanup"
      job_status_t: "queued" | "running" | "completed" | "failed" | "dead"
      platform_t:
        | "instagram"
        | "tiktok"
        | "youtube"
        | "linkedin"
        | "x"
        | "facebook"
      post_lifecycle_t:
        | "draft"
        | "review"
        | "scheduled"
        | "publishing"
        | "published"
        | "failed"
        | "analyzed"
      post_source_t: "imported" | "native"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      asset_kind_t: ["photo", "video", "screenshot", "testimonial", "proof"],
      integration_status_t: ["active", "expired", "revoked", "unsupported"],
      job_kind_t: [
        "sync",
        "transcode",
        "publish",
        "refresh_token",
        "finalize_deletion",
        "cleanup",
      ],
      job_status_t: ["queued", "running", "completed", "failed", "dead"],
      platform_t: [
        "instagram",
        "tiktok",
        "youtube",
        "linkedin",
        "x",
        "facebook",
      ],
      post_lifecycle_t: [
        "draft",
        "review",
        "scheduled",
        "publishing",
        "published",
        "failed",
        "analyzed",
      ],
      post_source_t: ["imported", "native"],
    },
  },
} as const
